import type { NextPage } from "next"
import Head from "next/head"

import { CreatorForm } from "@components/CreatorForm"

const Creator: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CreatorForm />
      </main>
    </div>
  )
}

export default Creator
