import type { NextPage } from "next"
import Head from "next/head"

import { MarketplaceGrid } from "@components/MarketplaceGrid"

const Marketplace: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <MarketplaceGrid />
      </main>
    </div>
  )
}

export default Marketplace
