import type { NextPage } from "next"
import Head from "next/head"

import { Marketplace } from "@components/Marketplace"

const MarketplacePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Marketplace />
      </main>
    </div>
  )
}

export default MarketplacePage
