import type { NextPage } from "next"
import Head from "next/head"

import { ProfileGrid } from "@components/ProfileGrid"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <ProfileGrid />
      </main>
    </div>
  )
}

export default Home
